# Generated by Django 2.2.10 on 2020-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
