# Generated by Django 2.2.10 on 2020-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200325_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
