# Generated by Django 2.2.10 on 2020-03-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('hub_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('x_co_ord', models.FloatField()),
                ('y_co_ord', models.FloatField()),
                ('area', models.CharField(max_length=50)),
                ('area_code', models.IntegerField()),
            ],
        ),
    ]
