# Generated by Django 2.2.10 on 2020-03-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0005_auto_20200308_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avail_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
