# Generated by Django 2.2.10 on 2020-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0006_auto_20200309_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='prod_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
