# Generated by Django 2.2.10 on 2020-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0007_auto_20200311_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_item.jpg', upload_to='prod_pics'),
        ),
    ]
