# Generated by Django 2.2.10 on 2020-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0008_auto_20200311_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avail_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
