# Generated by Django 2.2.10 on 2020-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0009_auto_20200311_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='profile_pic',
            field=models.ImageField(default='default_av.png', upload_to='merch_profile_pics'),
        ),
    ]
